
fdfs:
 so-timeout: 10000
 connect-timeout: 10000
 thumb-image:
  width: 150
  height: 150
 tracker-list:
  - 192.168.0.200:22122
 #webServerUrl: http://192.168.0.200/group1
 #webServerUrl: http://192.168.0.200/fastdfs/tracker/data
spring:
 servlet:
  multipart:
   max-request-size: 1024MB
   max-file-size: 1024MB
 datasource:
  username: root
  password: root
  url: jdbc:mysql:///test?serverTimezone=UTC